### ISSUE TITLE
ModuleNotFoundError: 

### ISSUE THREAD

**Issue by Saab953ltid** [PastVision/putmega#2]
Hi there, 

Thanks for the script however facing an issue.

C:\Users\User\Pictures>python main.py https://putme.ga/album/xxxxxxxxx.yyyyy
Traceback (most recent call last):
  File "C:\Users\User\Pictures\main.py", line 60, in <module>
    x.download()
  File "C:\Users\User\Pictures\main.py", line 24, in download
    pages = ceil(int(self.soup.find(
AttributeError: 'NoneType' object has no attribute 'text'
regards,

**Comment by Saab953ltid** [comment]
Solve works as expected only if you try to download the root folder, not a specific album if any.
So address should look like https://putme.ga/name and not if has https://putme.ga/album/...

**Comment by PastVision** [comment]
> Solve works as expected only if you try to download the root folder, not a specific album if any.
> So address should look like https://putme.ga/name and not if has https://putme.ga/album/...

Ahh, thanks for the information. It was just a casual project so i didn't bother with that. Glad that you tried the code. Cheers.
